{
  if (ew == null) {
    return null;
  }
  Throwable ex=null;
  Throwable cause=deserialize(ew.cause);
  try {
    Class exClass=Class.forName(ew.typeName);
    try {
      Constructor ctor=exClass.getDeclaredConstructor(new Class[]{String.class,Throwable.class});
      ctor.setAccessible(true);
      ex=(Throwable)ctor.newInstance(new Object[]{ew.message,cause});
    }
 catch (    Throwable e) {
      try {
        Constructor ctor=exClass.getDeclaredConstructor(new Class[]{String.class});
        ctor.setAccessible(true);
        ex=(Throwable)ctor.newInstance(new Object[]{ew.message});
        ex.initCause(cause);
      }
 catch (      Throwable e2) {
        try {
          Constructor ctor=exClass.getDeclaredConstructor(new Class[]{Throwable.class});
          ctor.setAccessible(true);
          ex=(Throwable)ctor.newInstance(new Object[]{cause});
          setField(exClass,"detailMessage",ex,ew.message);
        }
 catch (        Throwable e3) {
          try {
            Constructor ctor=exClass.getDeclaredConstructor(null);
            ctor.setAccessible(true);
            ex=(Throwable)ctor.newInstance(null);
            ex.initCause(cause);
            setField(exClass,"detailMessage",ex,ew.message);
          }
 catch (          Throwable e4) {
            this.log("Failed to deserialize exception of type '" + ew.typeName + "'; no available constructor",e4);
          }
        }
      }
    }
  }
 catch (  Throwable e) {
    this.log("Failed to deserialize exception of type '" + ew.typeName + "'",e);
  }
  if (ex == null) {
    ex=new RuntimeException(ew.typeName + ": " + ew.message,cause);
  }
  ex.setStackTrace(deserialize(ew.stackTrace));
  return ex;
}
