{
  log.clear();
  try (Resource rA=new Resource("A");Resource rB=new ResourceWithExceptionOnClose("B");Resource rC=new Resource("C")){
    rA.doSomething();
    rB.doSomething();
    rC.doSomething();
  }
 catch (  Exception e) {
    log.add(e.getMessage());
  }
 finally {
    log.add("finally");
  }
  assertContentsInOrder(log,"Open A","Open B","Open C","doSomething A","doSomething B","doSomething C","Close C","Close A","Exception in close B","finally");
}
