{
  failViaUncaughtException("fail_uncaught");
  failNow("failNow");
}
