{
  JavaScriptException t=new JavaScriptException((Object)"foo");
  assertTrue(t.isThrownSet());
  try {
    throwNative(t);
    fail();
  }
 catch (  JavaScriptException e) {
    assertSame(t,e);
  }
  t=new JavaScriptException("exception message");
  assertFalse(t.isThrownSet());
  try {
    throwNative(t);
    fail();
  }
 catch (  JavaScriptException e) {
    assertSame(t,e);
  }
}
