{
  try {
    return future.get();
  }
 catch (  ExecutionException e) {
    Throwable cause=e.getCause();
    if (cause instanceof RequestException) {
      throw (RequestException)cause;
    }
 else {
      throw new RuntimeException(e);
    }
  }
catch (  InterruptedException e) {
    throw new RuntimeException(e);
  }
}
