{
  RemoteServiceServletTestServiceAsync service=getAsyncService();
  delayTestFinishForRpc();
  service.throwUnknownRuntimeException(new AsyncCallback<Void>(){
    public void onFailure(    Throwable caught){
      assertTrue(caught instanceof InvocationException);
      finishTest();
    }
    public void onSuccess(    Void result){
      fail();
    }
  }
);
}
